name: app_generator_cartel1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-139.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dog.png
